# Generated by Django 5.2 on 2025-04-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stu_name', models.CharField(max_length=50)),
                ('Stu_email', models.EmailField(max_length=50)),
                ('Stu_address', models.CharField(max_length=200)),
                ('Stu_dis', models.CharField(max_length=200)),
                ('Stu_contact', models.IntegerField()),
                ('Stu_dob', models.DateField()),
                ('Stu_qualification', models.CharField(max_length=50)),
                ('Stu_gender', models.CharField(max_length=10)),
                ('Stu_image', models.ImageField(upload_to='images/')),
                ('Stu_document', models.FileField(upload_to='documents/')),
                ('Stu_password', models.CharField(max_length=50)),
            ],
        ),
    ]
