# Generated by Django 5.2 on 2025-04-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Stu_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Stu_contact',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='Stu_dis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Stu_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Stu_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='Stu_gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='Stu_image',
            field=models.ImageField(blank=True, null=True, upload_to='students/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Stu_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='Stu_password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='Stu_qualification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
